<<<<<<< HEAD
lb:
    image: nginx
    volumes:
      - './nginx.conf.d:/etc/nginx/conf.d'
      - '.:/var/www'
    links:
      - lolek
      - bolek
    ports:
      - 80:80
    restart: 'no'
    
lolek:
    image: tsentyrion/lolek
    volumes:
      - './server/www/lolek:/var/www/server/www/lolek'

   
 
bolek:
    image: tsentyrion/bolek
    volumes:
      - './server/www/lolek:/var/www/server/www/lolek'



=======
version: "3.3" 
services:
  loadballance:
    image: nginx:latest
    volumes:
    - './nginx.conf.d:/etc/nginx/conf.d'
    - '.:/usr/share/nginx/html'
    links:
      - bolek
      - lolek
    ports:
      - 80:80
  bolek:
    image: tsentyrion/bolek
  lolek:
    image: tsentyrion/lolek
>>>>>>> 8878d073e0924e12118aab1942a3bd924c5b25d4
